課題 06_学習管理アプリ
yuya-konkon/05_learning_plan pull request #1
Opened 2020-02-06 14:47 UTC by yuya-konkon

【期待する動作】
新規レコードの追加、エラーを2つ起動させる
【うまくいかない点 or エラーの内容】
新規タスクに追加できない、エラーを2つ表示できない
【自分なりに考えて試した点】
まず、出来ることからやろうと思って、
データベース、テーブルの作成、phpからデータベースに接続
タイトル、フォームの作成、未達成レコード(期限の表示も)を持ってきて表示するまではうまくできたのですが、

36行目から45行目が新規レコードの追加のコードなのですが、追加できず、ヒントいただきたいです。。
自分の中では、エラーがなければ実行するなので、実行自体はできていると思うのですが、データベースには追加されていないです。
確認する方法などもあったら教えいただければと思います。

タイトルと日付のエラーを2つ表示することができないので1つ(コードは日付のみ)で表示することはできました。反対にタイトルだけでも表示できました。

<img width="952" alt="スクリーンショット 2020-02-06 23 41 55" src="https://user-images.githubusercontent.com/58411049/73947098-4bfca200-493a-11ea-8f01-d0ca3cf13f06.png">
<img width="952" alt="スクリーンショット 2020-02-06 23 41 58" src="https://user-images.githubusercontent.com/58411049/73947241-7f3f3100-493a-11ea-802e-c292953ed388.png">

2020-02-06 15:22 UTC, kazu-taka requested changes
@yuya-konkon 
コメントしました！！

2020-02-06 15:22 UTC, kazu-taka commented on index.php
> +    $sql = "insert into plans (title, due_date, created_at, updated_at) values (:title, YYYY-MM-DD, now(), now())";
@yuya-konkon 
insertの部分ですが、titleの部分はバインドパラムを使用しているので正しいやり方ですが、due_dateのところもバイントパラムにしないといけません。
`YYYY-MM-DD`のところでエラーがおきていると思われます！
試しにtableplusで、`insert into plans (title, due_date, created_at, updated_at) values ('テスト', YYYY-MM-DD, now(), now())`等のSQLを試しに実行して確認してみるのもいいと思います！！

2020-02-06 15:22 UTC, kazu-taka commented on index.php
> +  // }
@yuya-konkon 
タスク名のエラーは、上記のif文3行のコメントを外してもらえればOKだと思います！
html内で$errorsをforeachで回して出力となります！

2020-02-07 01:18 UTC, yuya-konkon commented on index.php
> +    $sql = "insert into plans (title, due_date, created_at, updated_at) values (:title, YYYY-MM-DD, now(), now())";
due_dateを同じようにバインドパラムにしたら無効なパラメーターのエラーになりました。。
due_dateのバインドパラムを消して実行すると新規のタスクが追加出たので、due_dateのバインドパラムが間違っているとは思うのですが、タイトルと同じなのでなぜできないのかがわからないです。。

`  if (empty($errors)) {
    $sql = "insert into plans (title, due_date, created_at, updated_at) values (:title, due_date, now(), now())";
    $stmt = $dbh->prepare($sql);
    $stmt->bindParam(":title", $title);
    $stmt->bindParam(":due_date", $due_date);
    $stmt->execute();  ここがエラー

    header('Location: index.php');  ここがエラー
    exit;
  }
}`

<img width="952" alt="スクリーンショット 2020-02-07 10 12 33" src="https://user-images.githubusercontent.com/58411049/73992439-8560fc00-4992-11ea-8417-a495f60bb0f4.png">

2020-02-07 02:10 UTC, kazu-taka commented on index.php
> +    $sql = "insert into plans (title, due_date, created_at, updated_at) values (:title, due_date, now(), now())";
@yuya-konkon 
bindParamの使い方ですが、titleはうまくいっているけど、due_dateはうまくいっていないということですね。
titleとdue_dateを見比べてもらえると、1文字違うところがあります！
公式のドキュメントを見てみて下さい！！
https://www.php.net/manual/ja/pdostatement.bindparam.php

2020-02-07 14:33 UTC, yuya-konkon commented on index.php
> +    $sql = "insert into plans (title, due_date, created_at, updated_at) values (:title, due_date, now(), now())";
bindParamが理解できません！
`  $stmt->bindParam(":title", $title);
    $stmt->bindParam(":due_date", $due_date);`
を比べると1文字違うということでしょうか？
公式ドキュメントもどこを見たらいいのかわからないです😭

2020-02-07 14:54 UTC, kazu-taka commented on index.php
> +    $sql = "insert into plans (title, due_date, created_at, updated_at) values (:title, due_date, now(), now())";
@yuya-konkon 
bindParamで指定したい場合、SQLの内部に`:XXXX`形式で書きます！
タイトルは`:title`で書いていて、その後に`$stmt->bindParam(":title", $title);`で置き換えているのでOKです！
due_dateの場合、`:XXXX`形式で書かれていないので、問題がおきていると思われます！
公式ドキュメントの該当する部分のスクショを添付します！
<img width="1028" alt="スクリーンショット 2020-02-07 23 50 19" src="https://user-images.githubusercontent.com/5278718/74039459-31432f80-4a05-11ea-9532-724f56cf7859.png">

<img width="907" alt="pdo" src="https://user-images.githubusercontent.com/5278718/74039468-36a07a00-4a05-11ea-9c17-32bc1b0ff1b3.png">

2020-02-08 06:06 UTC, yuya-konkon commented on index.php
> +    $sql = "insert into plans (title, due_date, created_at, updated_at) values (:title, due_date, now(), now())";
@kazu-taka
なるほど！！！！！そういうことだったんですね！！
$_POSTの所と紐づいてると思ってたんですがsplのとのだったんですね！
やっと理解できました😭😭画像もわざわざありがとうございます😭😭😭

2020-02-11 01:16 UTC, kazu-taka requested changes
@yuya-konkon 
確認お願いします！！

2020-02-11 01:16 UTC, kazu-taka commented on edit.php
> +// var_dump($_SERVER);
@yuya-konkon 
こういう残骸は消した方がすっきりするので削除お願いします！！

2020-02-11 01:16 UTC, kazu-taka commented on edit.php
> +  // var_dump($errors);
@yuya-konkon 
ここの残骸もお願いします！

2020-02-11 01:16 UTC, kazu-taka commented on index.php
> +// echo $today;
@yuya-konkon 
このへんのコメントも全部削除お願いします！！

2020-02-11 01:16 UTC, kazu-taka commented on index.php
> +        <ul style="color:red;">
@yuya-konkon 
余裕があれば、ここもclassにしてcssを読み込むパターンに修正してみて下さい✨

2020-02-11 01:19 UTC, yuya-konkon commented on index.php
> +        <ul style="color:red;">
確認ありがとうございます！
コメント削除します！🙇‍♂️
最後のクラスにするのはcssファイルがあるからまとめたほうがスッキリする的な意味合いでしょうか！

2020-02-11 01:21 UTC, yuya-konkon commented on index.php
> +        <ul style="color:red;">
@kazu-taka
確認ありがとうございます！
コメント削除します！🙇‍♂️
最後のクラスにするのはcssファイルがあるからまとめたほうがスッキリする的な意味合いでしょうか！

2020-02-11 01:29 UTC, kazu-taka commented on index.php
> +        <ul style="color:red;">
@yuya-konkon 
CSSの授業でもやりましたが、直接styleで書いてしまうと後で修正する時に見つけるのが大変なため、外部のファイルに書くというのが一般的になってます✨
https://23seiki.gitbook.io/php/css/01#3-fairunisuru

2020-02-13 10:04 UTC, yuya-konkon commented on index.php
> +        <ul style="color:red;">
@kazu-taka
すみません！ありがとうございます！
修正したファイルの確認はできましたでしょうか？

2020-02-13 12:15 UTC, kazu-taka commented
@yuya-konkon 
![LGTM](https://lgtmoon.herokuapp.com/images/74730)

2020-02-13 13:28 UTC, merged